// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAduusI4Lqzux6Fz8-L6w8mopiZdrIsXl0',
    appId: '1:484640854174:web:97551001e1907ca019ab8f',
    messagingSenderId: '484640854174',
    projectId: 'kdlyrz-2ceef',
    authDomain: 'kdlyrz-2ceef.firebaseapp.com',
    storageBucket: 'kdlyrz-2ceef.firebasestorage.app',
    measurementId: 'G-5S4NLBHQBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDZPAgoQcwWTRvGBMNF2QeApgtebJZRsM',
    appId: '1:484640854174:android:d77dee133b39ae6519ab8f',
    messagingSenderId: '484640854174',
    projectId: 'kdlyrz-2ceef',
    storageBucket: 'kdlyrz-2ceef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrZHV80zyakGvMfJ9OMhzqxXDcXeeSGU',
    appId: '1:484640854174:ios:c1e1a81739b0a36119ab8f',
    messagingSenderId: '484640854174',
    projectId: 'kdlyrz-2ceef',
    storageBucket: 'kdlyrz-2ceef.firebasestorage.app',
    iosBundleId: 'com.example.kdlyrz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrZHV80zyakGvMfJ9OMhzqxXDcXeeSGU',
    appId: '1:484640854174:ios:c1e1a81739b0a36119ab8f',
    messagingSenderId: '484640854174',
    projectId: 'kdlyrz-2ceef',
    storageBucket: 'kdlyrz-2ceef.firebasestorage.app',
    iosBundleId: 'com.example.kdlyrz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAduusI4Lqzux6Fz8-L6w8mopiZdrIsXl0',
    appId: '1:484640854174:web:b4271fc2f0444cd319ab8f',
    messagingSenderId: '484640854174',
    projectId: 'kdlyrz-2ceef',
    authDomain: 'kdlyrz-2ceef.firebaseapp.com',
    storageBucket: 'kdlyrz-2ceef.firebasestorage.app',
    measurementId: 'G-EHQZ33YPGX',
  );
}
